### ISSUE TITLE
Todo, towards v1.0.0

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/elastic-ci-stack-for-aws#1]
- [ ] Zephyr specific docs on to use / update, etc the repo
- [ ] Setup CI workflow so changes will propagate (need to figure out 
- [ ] Deal with cleaning up and tracking AMI images
```
[galak@spiff ci-zephyr-buildkite]$ cat build/mappings.yml 
Mappings:
  AWSRegion2AMI:
    us-east-1 : { linux: ami-0a7cebc9922ef7516 }
```
- [ ] Handle setting of SuspendProcesses/AZRebalance on AutoScale group

```
make clean; make STACK_NAME=buildkite-zephyr
make STACK_NAME=buildkite-zephyr update-stack
```

**Comment by galak** [comment]
- [ ] Need more testing w/regards to `update-stack` and maintaining `BuildkiteAgentToken`.

one test on Jun 12 appears that `BuildkiteAgentToken` may need to be specified.

Verify in `Launch templates`

**Comment by galak** [comment]
- [ ] Verify how `update-stack` handles transition of jobs in flight.
